//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThriftHub.BLL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderStatusAudit
    {
        public int AuditID { get; set; }
        public int OrderID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string OldStatus { get; set; }
        public string NewStatus { get; set; }
        public string ChangedBy { get; set; }
        public System.DateTime ChangeDate { get; set; }
    }
}
