//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThriftHub.BLL.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class ThriftHubDBEntities2 : DbContext
    {
        public ThriftHubDBEntities2()
            : base("name=ThriftHubDBEntities2")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderStatusAudit> OrderStatusAudit { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<vw_ActiveProductListings> vw_ActiveProductListings { get; set; }
        public virtual DbSet<vw_CategorySalesSummary> vw_CategorySalesSummary { get; set; }
        public virtual DbSet<vw_OrderDetailsFull> vw_OrderDetailsFull { get; set; }
        public virtual DbSet<vw_ProductsWithSellerAndCategory> vw_ProductsWithSellerAndCategory { get; set; }
        public virtual DbSet<vw_SellerSalesSummary> vw_SellerSalesSummary { get; set; }
        public virtual DbSet<v_SellerProducts> v_SellerProducts { get; set; }
    }
}
