//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThriftHub.BLL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ActiveProductListings
    {
        public int ProductID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public string Condition { get; set; }
        public string Status { get; set; }
        public System.DateTime UploadDate { get; set; }
        public string ImageURL { get; set; }
        public int CategoryID { get; set; }
        public string CategoryName { get; set; }
        public int SellerID { get; set; }
        public string SellerName { get; set; }
        public decimal SellerAverageRating { get; set; }
    }
}
