//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThriftHub.BLL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_OrderDetailsFull
    {
        public int OrderID { get; set; }
        public int BuyerID { get; set; }
        public string BuyerName { get; set; }
        public System.DateTime OrderDate { get; set; }
        public decimal TotalAmount { get; set; }
        public string OrderStatus { get; set; }
        public int OrderDetailID { get; set; }
        public int ProductID { get; set; }
        public string ProductTitle { get; set; }
        public string ImageURL { get; set; }
        public decimal Amount { get; set; }
        public string PaymentMethod { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string PaymentStatus { get; set; }
        public int SellerID { get; set; }
        public string SellerName { get; set; }
    }
}
