//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThriftHub.BLL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_SellerSalesSummary
    {
        public int SellerID { get; set; }
        public string SellerName { get; set; }
        public string SellerEmail { get; set; }
        public decimal SellerAverageRating { get; set; }
        public Nullable<int> TotalProductsListed { get; set; }
        public Nullable<int> TotalItemsSold { get; set; }
        public decimal TotalRevenue { get; set; }
    }
}
